server:
  port: 7001

eureka:
  #server:
    #enable-self-preservation: false            #用来关闭自我保护机制，不推荐关闭
  instance:
    hostname: eureka7001.com #集群
    #hostname:  localhost #eureka服务端的实例名称eureka7001.com
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #此处取了localhost 和 7001。单机设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/


