spring:
  profiles:
    active:
      - dev
---
spring:
  profiles:dev 
  application:
    name:microservicecloud-config-hdu-dev
---
spring:
  profiles:test
  application:
    name:microservicecloud-config-hdu-test